apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-db-volume-claim 
spec:
  storageClassName: wordpress-db-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi