apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: wordpress-configmap-env
    envs:
      - wordpress.env

resources:
  - kustomization.yaml
  - svc-wordpress-loadbalancer.yaml
  - wordpress-deployment.yaml
  - wordpress-hpa.yaml
