apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  template:
    metadata:
      name: wordpress
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: wordpress-configmap-env
  selector:
    matchLabels:
      app: wordpress